language: python
os:
  - linux
#  - osx

compiler:
  - gcc
  - clang


python:
  - "2.7"
#  - "3.4"
  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "3.6"
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 -y
  - sudo apt-get install geos -y
  - sudo apt-get install libproj-dev libhdf5-serial-dev libpng12-dev -y
  - sudo apt-get install libgdal-dev gdal libatlas-dev libatlas-base-dev gfortran -y
#addons:
#  apt:
#    packages:
#    - gdal-bin
#    - libproj-dev
#    - libhdf5-serial-dev
#    - libpng12-dev
#    - libgdal-dev
#    - libatlas-dev
#    - libatlas-base-dev
#    - gfortran

#before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc     ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gdal     ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install geos     ; fi
#  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; pip install mock        ; fi

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install geopandas"
  - "pip install fiona"
  - "pip install shapely"
# command to run tests
script: pytest